version: '3.8'

services:
  # Laravel App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrms_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=my_hrms_management
      - DB_USERNAME=hrmsuser
      - DB_PASSWORD=Mypassword@#1234
    expose:
      - "9000"  # Laravel app runs on default PHP-FPM port (9000)

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: hrms_nginx
    restart: unless-stopped
    ports:
      - "81:81"  # Access this app via http://your-vps-ip:81
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: hrms_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_hrms_management
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hrmsuser
      MYSQL_PASSWORD: Mypassword@#1234
    ports:
      - "3211:3306"
    volumes:
      - db_data:/var/lib/mysql

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hrms_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"  # Access phpMyAdmin via http://your-vps-ip:8081
    depends_on:
      - db

volumes:
  db_data:
